config/routes.rb
Rails.application.routes.draw do
  resources :cates
  resources :items
  resources :cates
  resources :items do
    member do
      get :add_cart
    end
  end


  devise_for :managers
  devise_for :users


  root "items#index"

  # 第一層：購物車
  resources :items, :only => [:index, :show]

  # 上面的網址：
  # /statics/action/
  #
  # namespace裡面的網址：
  # dashboard/items/action


  # 第二層：dashboard
  namespace :dashboard do
    resources :orders

    # 第三層：admin
    namespace :admin do
      #現在是教學示例，建議:admin寫成亂碼，像是:sakwejh，這樣才不會被猜到
      # 一個系統在打時，建議從後面打到前面，例如先從管理介面開始打
      resources :items  # 要賣的東西
      resources :cates  # 要賣的東西的分類
      resources :orders # 訂單
      resources :users
      resources :managers
    end
  end
end

app/models/cate.rb
class Cate < ActiveRecord::Base
  has_many :items
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :cate

  has_attached_file :cover,
    styles: {
      original: "1024x1024>",
      cover: "300x300>",
      icon: "150x150#"
    },
    default_url: "/images/missing2.jpg"
  validates_attachment_content_type :cover, content_type: /\Aimage\/.*\z/
end

app/models/manager.rb
class Manager < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable #, :registerable,
         #:recoverable, :rememberable, :trackable, :validatable
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :order_items

  STATUS = [['New',1], ['Paying Procedure',2], ['Paid',3],['Shipped',4]]['Problem', 5]]
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :item
  belongs_to :user
  belongs_to :order
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable #,
         #:recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cates_controller.rb
class CatesController < ApplicationController
  before_action :set_cate, only: [:show, :edit, :update, :destroy]

  # GET /cates
  def index
    @cates = Cate.all
  end

  # GET /cates/1
  def show
  end

  # GET /cates/new
  def new
    @cate = Cate.new
  end

  # GET /cates/1/edit
  def edit
  end

  # POST /cates
  def create
    @cate = Cate.new(cate_params)

    if @cate.save
      redirect_to @cate, notice: 'Cate was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /cates/1
  def update
    if @cate.update(cate_params)
      redirect_to @cate, notice: 'Cate was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /cates/1
  def destroy
    @cate.destroy
    redirect_to cates_url, notice: 'Cate was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cate
      @cate = Cate.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def cate_params
      params[:cate]
    end
end

app/controllers/dashboard/admin/admin_controller.rb
class Dashboard::Admin::AdminController < ApplicationController
  before_action :authenticate_manager!
  layout 'admin'
end

app/controllers/dashboard/admin/cates_controller.rb
class Dashboard::Admin::CatesController < Dashboard::Admin::AdminController

end

app/controllers/dashboard/admin/items_controller.rb
class Dashboard::Admin::ItemsController < Dashboard::Admin::AdminController
  def index
    @items = @paginate = Item.order('id DESC').includes(:cate).paginate(page: params[:page])
  end

  def new
    @item = Item.new
  end

  def edit
    @item = Item.find(params[:id])
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to dashboard_admin_items_path
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to dashboard_admin_items_path
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to dashboard_admin_items_path
  end
end

private

def item_params
  params.require(:item).permit!
end

app/controllers/dashboard/admin/managers_controller.rb
class Dashboard::Admin::ManagersController < Dashboard::Admin::AdminController

end

app/controllers/dashboard/admin/orders_controller.rb
class Dashboard::Admin::OrdersController < Dashboard::Admin::AdminController

end

app/controllers/dashboard/admin/users_controller.rb
class Dashboard::Admin::UsersController < Dashboard::Admin::AdminController

end

app/controllers/dashboard/dashboard_controller.rb
class Dashboard::DashboardController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/dashboard/orders_controller.rb
class Dashboard::OrdersController < Dashboard::DashboardController

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def add_cart
    session[:cart] ||= {}
    item = Item.where(id: params[:id]).first

    if item
      key = item.id.to_s
      session[:cart][key] ||= 0
      session[:cart][key] += 1
    end

    render json: { counter: session[:cart].size }.to_json
  end


  # GET /items
  def index
    @items = @paginate = Item.includes(:cate).paginate(page: params[:page])
  end

  # GET /items/1
  def show
    @item = Item.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def get_cart_count
    session[:cart] ? session[:cart].size : 0
  end

end

app/helpers/cates_helper.rb
module CatesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/cates/_form.html.erb
<%= form_for(@cate) do |f| %>
  <% if @cate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cate.errors.count, "error") %> prohibited this cate from being saved:</h2>

      <ul>
      <% @cate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cates/edit.html.erb
<h1>Editing Cate</h1>

<%= render 'form' %>

<%= link_to 'Show', @cate %> |
<%= link_to 'Back', cates_path %>

app/views/cates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cates</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cates.each do |cate| %>
      <tr>
        <td><%= link_to 'Show', cate %></td>
        <td><%= link_to 'Edit', edit_cate_path(cate) %></td>
        <td><%= link_to 'Destroy', cate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cate', new_cate_path %>

app/views/cates/new.html.erb
<h1>New Cate</h1>

<%= render 'form' %>

<%= link_to 'Back', cates_path %>

app/views/cates/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_cate_path(@cate) %> |
<%= link_to 'Back', cates_path %>

app/views/dashboard/admin/items/edit.html.erb
<h1>Editing Item</h1>

<%= form_for @item, url: dashboard_admin_item_path, method: :patch  do |f| %>
  Name： <%= f.text_field :name %><br>
  Price： <%= f.number_field :price %><br>
  Pic： <%= f.file_field :cover %><br>
  Category： <%= f.select :cate_id, Cate.all.map{|c| [c.name, c.id]} %>

  <button type="submit" >Submit</button>
<% end %>

app/views/dashboard/admin/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Product Listing</h1>

<table>
  <thead>
    <tr>
      <th>id</th>
      <th>Category</th>
      <th>Pic</th>
      <th>Name</th>
      <th>Price</th>
      <th>Manage</th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.id %></td>
        <td><%= item.cate.name %></td>
        <td><%= image_tag item.cover.url(:icon), width: 150, height: 150 %></td>
        <td><%= item.name %></td>
        <td><%= item.price %></td>
        <td>
          <%= link_to 'Edit', edit_dashboard_admin_item_path(item) %>
          <%= link_to 'Destroy', dashboard_admin_item_path(item), method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_dashboard_admin_item_path %>

app/views/dashboard/admin/items/new.html.erb
<h1>New Item</h1>

<%= form_for @item, dashboard_admin_items_path, method: :post  do |f| %>
  Name： <%= f.text_field :name %><br>
  Price： <%= f.number_field :price %>
  <button type="submit" >Submit</button>
<% end %>

app/views/dashboard/admin/items/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<% content_for :header do %>
<style>
  ul.items, ul.items li{
    list-style: none;
    padding: 0;
    margin: 0;
  }
  ul.items li{
    display: block;
    float: left;
    border: 1px #ccc solid;
    border-radius: 6px;
    width: 300px;
    height: 400px;
    margin: 4px 0 0 4px;
    text-align: center;
  }
  ul.items li img{
    width: 300px;
    height: 300px;
    display: block;
    border-radius: 8px;
  }
  ul.items li .name{
    display: block;
  }
  ul.items li a{
    display: inner-block;
    background: #ccccff;
    padding: 4px 8px;
    border-radius: 3px;
  }
</style>


<script>
  $( document ).ready(function(){
   $('.add_cart').click(function(){
     $.getJSON('/items/' + $(this).attr('data-value') + '/add_cart', function(json){
      $('#cart_counter').html(json.counter);
    });
    return false;
   });
  })
</script>
<% end %>

<h1>Listing Items</h1>

<ul class="items">
  <% @items.each do |item| %>
    <li>
      <%= image_tag(item.cover.url(:icon), size: "300x300") %>
      <span class="name"><%= item.name %>(<%= item.price %>)</span>
      <a href="#" class="add_cart" data-value="<%= item.id %>">Add To Cart</a>
    </li>
  <% end %>
</ul>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JCcart</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<h1>Administration Panel：Admin</h1>

Hi! <%= current_manager.email %>, <%= link_to "Log Out", destroy_manager_session_path, method: "delete" %>

<hr>

<ul>
  <li><%= link_to "Product Management", dashboard_admin_items_path %></li>
</ul>

<%= will_paginate @paginate if @paginate %>

<hr>

<%= yield %>

<hr>

<%= will_paginate @paginate if @paginate %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FastShop</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= yield :header %>
</head>
<body>

<h1>General Page: Public</h1>
<div>Shopping Cart：<span id="cart_counter"><%= get_cart_count %></span></div>
<br>
<%= session[:cart] %>

<% if current_user %>
  Hi! <%= current_user.email %>, <%= link_to "Log Out", destroy_user_session_path, method: "delete" %>
<% else %>
  <%= link_to "Log In", new_user_session_path %>, <%= link_to "Sign Up", new_user_registration_path %>
<% end %>

<hr>

<%= will_paginate @paginate if @paginate %>

<hr>

<%= yield %>

<!-- <hr>

<%#= will_paginate @paginate if @paginate %>

<hr> -->

</body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JCcart</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<h1>User Dashboard: Dashboard</h1>

Hi! <%= current_user.email %>, <%= link_to "Log Out", destroy_user_session_path, method: "delete" %>

<%= will_paginate @paginate if @paginate %>

<hr>

<%= yield %>

<hr>

<%= will_paginate @paginate if @paginate %>
</body>
</html>